sudo: required
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: node_js

script: >
    npm run test
notifications:
  email:
    recipients:
      - yaniv.efraim@gmail.com